INSERT INTO clothtype (clothtypeid, servicetypeid, "name") VALUES
  (1, 1, 'Almofada'),
  (2, 1, 'Bata'),
  (3, 1, 'Blaser (Senhor / Senhora)'),
  (4, 1, 'Blusa Simples'),
  (5, 1, 'Blusa / Camisa de seda'),
  (6, 1, 'Boneco de Peluche Grande'),
  (7, 1, 'Boneco de Peluche Médio'),
  (8, 1, 'Boneco de Peluche Pequeno'),
  (9, 1, 'Boxer'),
  (10, 1, 'Calça (Senhor/Senhora)'),
  (11, 1, 'Calça de Ganga Jeans (Senhor/Senhora)'),
  (12, 1, 'Calça de Linho (Senhor/Senhora)'),
  (13, 1, 'Calça de Seda'),
  (14, 1, 'Calção Bermuda de Algodão'),
  (15, 1, 'Calção Bermuda de Ganga'),
  (16, 1, 'Calção Bermuda de Linho'),
  (17, 1, 'Calção Bermuda de Seda'),
  (18, 1, 'Camisa Senhor/Senhora'),
  (19, 1, 'Camisa Africana'),
  (20, 1, 'Camisa de Ganga'),
  (21, 1, 'Camiseiro Senhor/Senhora'),
  (22, 1, 'Saco de Bebê/Saco de Fraldas'),
  (23, 1, 'Casaco Senhor/Senhora'),
  (24, 1, 'Casaco de Linho'),
  (25, 1, 'Casaco Smoking'),
  (26, 1, 'Casaco Comprido Senhor/Senhora'),
  (27, 1, 'Casaco Balção Gabardine'),
  (28, 1, 'Cesto Simples'),
  (29, 1, 'Cesto Decoração'),
  (30, 1, 'Chapéu'),
  (31, 1, 'Cobertor Colcha (Casal)'),
  (32, 1, 'Cobertor Colcha (Solteiro)'),
  (33, 1, 'Cortinados com Forro'),
  (34, 1, 'Cortinados Simples'),
  (35, 1, 'Cortinados Transparentes'),
  (36, 1, 'Cuecas'),
  (37, 1, 'Echarpes'),
  (38, 1, 'Edredão (Casal)'),
  (39, 1, 'Edredão (Solteiro)'),
  (40, 1, 'Edredão (Criança)'),
  (41, 1, 'Fato Africano'),
  (42, 1, 'Fato (Senhor/Senhora)'),
  (43, 1, 'Fato de Seda (Senhor/Senhora)'),
  (44, 1, 'Fato de Linho (Senhor/Senhora)'),
  (45, 1, 'Forro de Alcofa'),
  (46, 1, 'Forro de Cadeira de Festa'),
  (47, 1, 'Forro de Cadeirão'),
  (48, 1, 'Forro de Colchão (Casal)'),
  (49, 1, 'Forro de Colchão (Solteiro)'),
  (50, 1, 'Forro de Sofá (1 Lugar)'),
  (51, 1, 'Forro de Sofá (2 Lugares)'),
  (52, 1, 'Forro de Sofá (3 ou Mais Lugares)'),
  (53, 1, 'Gabardine'),
  (54, 1, 'Gravata Normal'),
  (55, 1, 'Gravata de Seda'),
  (56, 1, 'Lençol de Casal (Conjunto)'),
  (57, 1, 'Lençol de Casal (Unidade)'),
  (58, 1, 'Lençol de Solteiro (Conjunto)'),
  (59, 1, 'Lençol de Solteiro (Unidade)'),
  (60, 1, 'Macacão Jardineira'),
  (61, 1, 'Meias'),
  (62, 1, 'Pijama'),
  (63, 1, 'Pólo'),
  (64, 1, 'Ropão Robe'),
  (65, 1, 'Saia Formal / Traje da Noite'),
  (66, 1, 'Saia de Linho'),
  (67, 1, 'Saia de Seda'),
  (68, 1, 'Saia Simples'),
  (69, 1, 'Tapetes'),
  (70, 1, 'T-Shirt Top (Senhor/Senhora)'),
  (71, 1, 'Toalha de Banho Grande'),
  (72, 1, 'Toalha de Banho Médio'),
  (73, 1, 'Toalha de Banho Pequena'),
  (74, 1, 'Toalha de Mesa de Linho/Seda (4 Lugares)'),
  (75, 1, 'Toalha de Mesa de Linho/Seda (6 Lugares)'),
  (76, 1, 'Toalha de Mesa de Linho/Seda (8 Lugares)'),
  (77, 1, 'Toalha de Mesa de Linho (12 Lugares)'),
  (78, 1, 'Toalha de Mesa de Linho (24 Lugares)'),
  (79, 1, 'Toalha de Mesa Normal (4 Lugares)'),
  (80, 1, 'Toalha de Mesa Normal (6 Lugares)'),
  (81, 1, 'Toalha de Mesa Normal (8 Lugares)'),
  (82, 1, 'Toalha de Mesa Normal (12 Lugares)'),
  (83, 1, 'Toalha de Mesa Normal (24 Lugares)'),
  (84, 1, 'Vestido de Batismo Comu/ Simples'),
  (85, 1, 'Vestido de Batismo Comu/ Volumoso'),
  (86, 1, 'Vestido de Linho'),
  (87, 1, 'Vestido de Noite Especial'),
  (88, 1, 'Vestido de Noite Especial Volumoso'),
  (89, 1, 'Vestido de Noiva Simples'),
  (90, 1, 'Vestido de Noiva Volumoso'),
  (91, 1, 'Vestido de Criança Especial'),
  (92, 1, 'Vestido de Noite Normal'),
  (93, 1, 'Vestido de Noite Simples'),
  (95, 1, 'Vestido de Noite Volumoso'),
  (96, 2, 'Não Especificado');
