INSERT INTO treatmenttype (treatmenttypeid, servicetypeid, "name") VALUES
  (1, 1, 'Tratamento Normal'),
  (2, 1, 'Passar a Ferro'),
  (3, 2, 'Bainha de Calça a Mão'),
  (4, 2, 'Bainha Dobrada'),
  (5, 2, 'Bainha Vestido'),
  (6, 2, 'Ajuste de Cintura de Calça/Saia'),
  (7, 2, 'Ajuste de Calça'),
  (8, 2, 'Ajuste de Vestido'),
  (9, 2, 'Ajuste de Vestido de Noiva'),
  (10, 2, 'Ajuste de Saia'),
  (11, 2, 'Virar a Gola da Camisa'),
  (12, 2, 'Pequenos Arranjos'),
  (13, 2, 'Ajuste Completo do Casaco'),
  (14, 2, 'Ajuste de Camisa'),
  (15, 2, 'Ajuste de Colete'),
  (16, 2, 'Ajuste de Manga de Camisa'),
  (17, 2, 'Botão Cada'),
  (18, 2, 'Ajuste de Boca'),
  (19, 2, 'Fecho'),
  (20, 2, 'Ajuste de Peito de Vestido'),
  (21, 2, 'Ajuste de Fato Completo'),
  (22, 2, 'Ajuste de Manga de Casaco');
